### ISSUE TITLE
Update to Version 2.0 breaks my MAUI app

### ISSUE THREAD

**Issue by ThysBrits** [MindscapeHQ/raygun4maui#17]
I updated my NuGet package from 1.4.2 to 2.0.0 today, and immediately get the following error:
Error	CS1061	'MauiAppBuilder' does not contain a definition for 'AddRaygun4Maui' and no accessible extension method 'AddRaygun4Maui' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?)    XXXXXXXXXXXXXXXX (net8.0-android34.0), XXXXXXXXXXXXXXXX (net8.0-windows10.0.19041.0)	C:\XXXXXXXXXXXXXXXX\MauiProgram.cs	33	Active

Is there documentation for upgrading to version 2.0.0?

**Comment by ThysBrits** [comment]
When I update my code as follows (old code commented out):
```
//.AddRaygun4Maui(config.GetValue<string>("RaygunApiKey"));
.AddRaygun(settings =>
{
		settings.RaygunSettings.ApiKey = config.GetValue<string>("RaygunApiKey");
});
```

I get the following error at runtime:
_You should only call 'AddRaygun4maui' once in your app_

**Comment by ProRedCat** [comment]
There have been some breaking API changes as you've countered with the AddRaygun4Maui. For 

Currently, we are looking into the issue where .Attach appears to be called twice. This is likely due to build being called twice either by a 3rd party package or in your setup process.

I'll post an update once we've resolved this for visibility for others who may encounter this.

**Comment by ThysBrits** [comment]
The problem though is that I didn't change anything in my app from version 1.4.2, which I upgrade from, except for the one line of code with the changed .AddRaygun, to work with version 2.0.0. Everything else is as it was, and was working fine. So why is the new version not working?

**Comment by ProRedCat** [comment]
This is a **major** version bump from v1.4.2 to v2.0.0 as we added Real User Monitoring support and some additional enhancements to Crash Reporting. With these changes, some behavior was modified, such as .AddRaygun4Maui transitioning to .AddRaygun. One of these changes also affected how we initialize the Raygun4MauiClient. 

Instead of calling .Attach when you call .AddRaygun4Maui we moved that responsibility to a new initializing service seen [here](https://github.com/MindscapeHQ/raygun4maui/blob/master/Raygun4Maui/RaygunClientInitializeService.cs). When builder.build() is called in a MAUI application all registered implementations of the IMauiInitializeService are invoked. This means if build is called more than once, which is not correct practice, the client can be attached twice causing this issue.

This is likely what's happening, so you should make sure that you are only calling build when you call return.

**Comment by ThysBrits** [comment]
As commented above, the cause was eventually found to be calling the .Build() method more than once.
